config/routes.rb
Petpicker::Application.routes.draw do
root 'pets#index'
resources :pets

end

app/models/pet.rb
class Pet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
	def index
		@pets = Pet.all
	end

	def new
		@pet = Pet.new
	end

	def create
		Pet.create(pet_params)
		redirect_to root_path
	end

	private

	def pet_params
		params.require(:pet).permit(:name, :reason)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petpicker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--begin navbar -->

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
 
      <%= link_to 'PetPicker', root_path, :class => 'navbar-brand' %>
    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
      <li>
        <%= link_to new_pet_path do %>
        Suggest a Pet
      </li>
      <% end %>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--end navbar -->
<div class="booyah-box col-xs-10 col-xs-offset-1 green">
  <h1>Help us pick the perfect pet</h1>
  <p>My kids have launched an intense begging campaign for a pet.</p>
  <p>Suggest a pet and tell me why it's the perfect pet.</p>
</div>
<!--end navbar -->
<%= yield %>
  
</body>
</html>

app/views/pets/index.html.erb
<% @pets.each do |pet| %>
<div class="booyah-box col-xs-8 col-xs-offset-2">
	<h1><%= pet.name %></h1><br />
	<p><%= pet.reason %></p><br />
</div>


<% end %>

app/views/pets/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Suggest a Pet</h1>
	<%= simple_form_for @pet do |f| %>
		<%= f.input :name %>
		<%= f.input :reason %>
		<br />
		<%= f.submit 'Create', :class => 'btn btn-primary' %>
	<% end %>
</div>